// 这是您的产品数据库文件
// 以后有新产品，直接复制一行加在下面就行，不需要动网页代码

const productData = [
{id:1,cas:"77-73-6",cat:"Additives",en:{name:"Dicyclopentadiene (DCPD)",app:"Epoxy resin modification, Chemical intermediates"},cn:{name:"双环戊二烯 (DCPD)",app:"环氧树脂改性，化工中间体"}},
{id:2,cas:"69-72-7",cat:"Pharma",en:{name:"Salicylic acid",app:"Pharmaceuticals, Dyes, Fragrances"},cn:{name:"水杨酸",app:"医药、日化、染料香料合成"}},
{id:3,cas:"/",cat:"Additives",en:{name:"C5 petroleum resin",app:"Adhesives, Road marking paint, Rubber"},cn:{name:"C5 石油树脂",app:"胶粘剂、路标漆、橡胶"}},
{id:4,cas:"/",cat:"Additives",en:{name:"C9 petroleum resin",app:"Printing inks, Coatings, Adhesives"},cn:{name:"C9 石油树脂",app:"油墨、涂料、胶粘剂"}},
{id:5,cas:"119-36-8",cat:"Pharma",en:{name:"Methyl salicylate",app:"Pharmaceuticals, Ointments, Personal Care"},cn:{name:"水杨酸甲酯",app:"药油、膏药、护理品"}},
{id:6,cas:"54-21-7",cat:"Pharma",en:{name:"Sodium salicylate",app:"Pharmaceuticals (Aspirin), Preservatives"},cn:{name:"水杨酸钠",app:"阿司匹林原料、防腐剂"}},
{id:7,cas:"98-86-2",cat:"Pharma",en:{name:"Acetophenone",app:"Pharmaceuticals, Fragrances, Resins"},cn:{name:"苯乙酮",app:"医药、香料、特种树脂"}},
{id:8,cas:"67-68-5",cat:"Solvents",en:{name:"Dimethyl sulfoxide (DMSO)",app:"Solvents, Chemical synthesis"},cn:{name:"二甲基亚砜 (DMSO)",app:"非质子极性溶剂、化工合成"}},
{id:9,cas:"122-20-3",cat:"Additives",en:{name:"Triisopropanolamine (TIPA)",app:"Cement grinding aids, Concrete admixtures"},cn:{name:"三异丙醇胺 (TIPA)",app:"水泥助磨剂、混凝土外加剂"}},
{id:10,cas:"6712-98-7",cat:"Additives",en:{name:"Diethanolisopropanolamine (DEIPA)",app:"Cement grinding aids, Concrete admixtures"},cn:{name:"二乙醇单异丙醇胺 (DEIPA)",app:"水泥助磨剂、混凝土外加剂"}},
{id:11,cas:"5343-92-0",cat:"Additives",en:{name:"1,2-Pentanediol (1,2-PDO)",app:"Moisturizers, Preservatives"},cn:{name:"1,2-戊二醇",app:"保湿剂、防腐剂"}},
{id:12,cas:"111-29-5",cat:"Additives",en:{name:"1,5-Pentanediol (1,5-PDO)",app:"Polyester polyols, Plasticizers"},cn:{name:"1,5-戊二醇",app:"聚酯多元醇、增塑剂"}},
{id:13,cas:"542-28-9",cat:"Pharma",en:{name:"Delta-Valerolactone",app:"Pharmaceutical intermediates, Fine chemicals"},cn:{name:"δ-戊内酯",app:"医药中间体、精细化工"}},
{id:14,cas:"75-75-2",cat:"Pharma",en:{name:"Methanesulfonic acid (MSA)",app:"Electroplating, Metal treatment, Pharma intermediates"},cn:{name:"甲基磺酸 (MSA)",app:"电镀、金属处理、医药农药中间体"}},
{id:15,cas:"38083-17-9",cat:"Pharma",en:{name:"Climbazole",app:"Anti-dandruff shampoos, Fungicides"},cn:{name:"氯咪巴唑",app:"去屑洗发水、抗真菌剂"}},
{id:16,cas:"/",cat:"Additives",en:{name:"Polyether polyols",app:"PU Foams (Soft/Rigid)"},cn:{name:"聚醚多元醇",app:"聚氨酯软泡/硬泡"}},
{id:17,cas:"/",cat:"Additives",en:{name:"Polyetheramines (PEA)",app:"Epoxy curing agents, Wind power composites"},cn:{name:"聚醚胺 (PEA)",app:"环氧树脂固化剂、风电复合材料"}},
{id:18,cas:"123-72-8",cat:"Solvents",en:{name:"N-Butyraldehyde",app:"Plasticizers, Coatings, Inks, Pharma/Daily chemicals"},cn:{name:"正丁醛",app:"增塑剂、涂料、油墨"}},
{id:19,cas:"78-84-2",cat:"Solvents",en:{name:"Isobutyraldehyde",app:"Synthesis of Neopentyl glycol (NPG)"},cn:{name:"异丁醛",app:"合成新戊二醇 (NPG)"}},
{id:20,cas:"110-87-2",cat:"Pharma",en:{name:"3,4-Dihydro-2H-Pyran (DHP)",app:"Hydroxy protective agent (Pharma/Agro)"},cn:{name:"3,4-二氢-2H-吡喃 (DHP)",app:"羟基保护剂"}},
{id:22,cas:"100-51-6",cat:"Solvents",en:{name:"Benzyl alcohol",app:"Coatings, Inks, Pharmaceuticals, Fragrances"},cn:{name:"苯甲醇",app:"涂料、油墨、医药、香料"}},
{id:23,cas:"100-52-7",cat:"Fragrance",en:{name:"Benzaldehyde",app:"Fragrances, Pharmaceutical intermediates"},cn:{name:"苯甲醛",app:"香料、医药中间体"}},
{id:24,cas:"65-85-0",cat:"Additives",en:{name:"Benzoic Acid",app:"Food preservatives, Industrial intermediates"},cn:{name:"苯甲酸",app:"食品防腐剂、工业中间体"}},
{id:25,cas:"100-47-0",cat:"Agro",en:{name:"Benzonitrile",app:"Agrochemical intermediates"},cn:{name:"苯甲腈",app:"农药中间体"}},
{id:26,cas:"98-00-0",cat:"Additives",en:{name:"Furfuryl alcohol",app:"Furan resins, Casting materials"},cn:{name:"糠醇",app:"呋喃树脂、铸造材料"}},
{id:27,cas:"98-01-1",cat:"Additives",en:{name:"Furfural",app:"Synthesis of Furfuryl alcohol, Casting industry"},cn:{name:"糠醛",app:"加氢制糠醇、铸造行业"}},
{id:29,cas:"109-99-9",cat:"Solvents",en:{name:"Tetrahydrofuran (THF)",app:"Raw material for PTMEG, Solvents"},cn:{name:"四氢呋喃 (THF)",app:"PTMEG原料、溶剂"}},
{id:30,cas:"96-47-9",cat:"Solvents",en:{name:"2-Methyl THF",app:"Pharma solvents, Bio-based green solvents"},cn:{name:"2-甲基四氢呋喃",app:"医药工艺溶剂、生物基溶剂"}},
{id:31,cas:"124-41-4",cat:"Additives",en:{name:"Sodium methylate",app:"Biodiesel, Organic synthesis"},cn:{name:"甲醇钠",app:"生物柴油、有机合成"}},
{id:34,cas:"16940-66-2",cat:"Pharma",en:{name:"Sodium borohydride",app:"Paper pulp bleaching, Pharma/Agro synthesis"},cn:{name:"硼氢化钠",app:"纸浆漂白、医药/农药合成"}},
{id:36,cas:"75-65-0",cat:"Solvents",en:{name:"Tert-Butanol",app:"MTBE/ETBE production, Organic intermediates"},cn:{name:"叔丁醇",app:"生产MTBE/ETBE、有机合成"}},
{id:37,cas:"865-48-5",cat:"Additives",en:{name:"Sodium tert-butoxide",app:"Catalysts for organic synthesis"},cn:{name:"叔丁醇钠",app:"有机合成碱催化剂"}},
{id:38,cas:"865-47-4",cat:"Additives",en:{name:"Potassium tert-butoxide",app:"Strong alkaline catalysts, Pharma/Agro R&D"},cn:{name:"叔丁醇钾",app:"高端有机合成强碱"}},
{id:39,cas:"1310-58-3",cat:"Additives",en:{name:"Potassium hydroxide (KOH)",app:"Potassium salts, Liquid fertilizers, Detergents"},cn:{name:"氢氧化钾 (KOH)",app:"钾盐制造、液体复合肥"}},
{id:40,cas:"584-08-7",cat:"Additives",en:{name:"Potassium carbonate",app:"Glass, Fertilizers, Food additives, Detergents"},cn:{name:"碳酸钾",app:"玻璃、化肥、食品添加剂"}},
{id:42,cas:"64-19-7",cat:"Solvents",en:{name:"Acetic acid",app:"VAM, PTA, Acetates, Acetic anhydride production"},cn:{name:"乙酸 (冰醋酸)",app:"醋酸乙烯、PTA、醋酸酯类"}},
{id:43,cas:"96-34-4",cat:"Agro",en:{name:"Methyl chloroacetate",app:"Agrochemical synthesis (Herbicides, Insecticides)"},cn:{name:"氯乙酸甲酯",app:"农药合成（草甘膦、乐果）"}},
{id:44,cas:"105-39-5",cat:"Agro",en:{name:"Ethyl chloroacetate",app:"Agrochemical synthesis (Herbicides, Insecticides)"},cn:{name:"氯乙酸乙酯",app:"合成除草剂、杀虫剂"}},
{id:45,cas:"149-73-5",cat:"Agro",en:{name:"Trimethyl orthoformate",app:"Vitamins/Pharma synthesis, Agrochemicals"},cn:{name:"原甲酸三甲酯",app:"维生素合成、农药"}},
{id:48,cas:"629-11-8",cat:"Additives",en:{name:"1,6-Hexanediol (HDOL)",app:"Polyurethanes, Polyesters, UV/EB curing materials"},cn:{name:"1,6-己二醇 (HDOL)",app:"聚氨酯、聚酯、UV固化材料"}},
{id:50,cas:"620-19-9",cat:"Pharma",en:{name:"3-Methyl benzyl chloride",app:"Pharmaceutical intermediates"},cn:{name:"3-甲基苄基氯",app:"医药中间体"}},
{id:51,cas:"103694-68-4",cat:"Fragrance",en:{name:"Majantol",app:"Fragrances (Citrus-Floral notes)"},cn:{name:"甲基壬乙醛 (Majantol)",app:"香精香料（柑橘花香）"}},
{id:54,cas:"91-10-1",cat:"Additives",en:{name:"2,6-dimethylphenol (DMP)",app:"Polyphenylene ether (PPO/PPE) synthesis"},cn:{name:"2,6-二甲基苯酚",app:"聚苯醚 (PPO) 合成"}},
{id:55,cas:"558-30-5",cat:"Pharma",en:{name:"Isobutylene oxide (IBO)",app:"Pharmaceutical synthesis"},cn:{name:"异丁烯环氧化物",app:"医药合成（叔丁基）"}},
{id:56,cas:"107-18-6",cat:"Additives",en:{name:"Allyl alcohol",app:"Glycerol production, Allylic resins, Plasticizers"},cn:{name:"烯丙醇",app:"甘油、烯丙基树脂、增塑剂"}},
{id:60,cas:"118-71-8",cat:"Additives",en:{name:"Maltol",app:"Food & Beverage additives"},cn:{name:"麦芽酚",app:"食品饮料添加剂"}},
{id:61,cas:"4940-11-8",cat:"Additives",en:{name:"Ethyl Maltol",app:"Flavor enhancers"},cn:{name:"乙基麦芽酚",app:"增香剂"}},
{id:62,cas:"28940-11-6",cat:"Fragrance",en:{name:"Watermelon ketone",app:"Perfumes, Daily chemicals"},cn:{name:"西瓜酮",app:"香水、日化"}},
{id:63,cas:"1222-05-5",cat:"Fragrance",en:{name:"Galaxolide",app:"Perfumes, Personal care products"},cn:{name:"佳乐麝香",app:"香水、个人护理品"}},
{id:64,cas:"57-55-6",cat:"Solvents",en:{name:"Propylene glycol (PG)",app:"UPR Resins, Food & Beverage, Cosmetics, Pharma"},cn:{name:"丙二醇 (PG)",app:"不饱和树脂、食品、化妆品"}},
{id:65,cas:"25265-71-8",cat:"Solvents",en:{name:"Dipropylene glycol (DPG)",app:"Daily chemicals, Fragrance carriers"},cn:{name:"二丙二醇 (DPG)",app:"日化、香精载体"}},
{id:66,cas:"108-32-7",cat:"Solvents",en:{name:"Propylene Carbonate (PC)",app:"Lithium battery electrolytes, Coatings, Adhesives"},cn:{name:"碳酸丙烯酯 (PC)",app:"锂电电解液、涂料、胶粘剂"}},
{id:67,cas:"7664-38-2",cat:"Additives",en:{name:"Phosphoric acid",app:"Fertilizers, Food industry, Metal treatment"},cn:{name:"磷酸",app:"化肥、食品工业、金属处理"}},
{id:68,cas:"77-92-9",cat:"Additives",en:{name:"Citric acid",app:"Food & Beverage, Pharma, Detergents"},cn:{name:"柠檬酸",app:"食品饮料、医药、洗涤剂"}},
{id:69,cas:"124-04-9",cat:"Additives",en:{name:"Adipic acid",app:"Nylon 66, Polyurethanes, Plasticizers"},cn:{name:"己二酸",app:"尼龙66、聚氨酯、增塑剂"}},
{id:70,cas:"107-15-3",cat:"Pharma",en:{name:"Ethylenediamine (EDA)",app:"Chelating agents (EDTA), Epoxy curing, Polyamides"},cn:{name:"乙二胺 (EDA)",app:"螯合剂、固化剂、聚酰胺"}},
{id:72,cas:"11138-66-2",cat:"Additives",en:{name:"Xanthan gum",app:"Food thickeners, Oil drilling mud"},cn:{name:"黄原胶",app:"食品增稠剂、石油钻井泥浆"}},
{id:74,cas:"87-02-5",cat:"Dyes",en:{name:"J acid",app:"Dye intermediates (Direct, Reactive, Azo dyes)"},cn:{name:"J 酸",app:"染料中间体（活性、直接染料）"}},
{id:75,cas:"90-20-0",cat:"Dyes",en:{name:"H acid",app:"Dye intermediates (Reactive, Acid, Direct dyes)"},cn:{name:"H 酸",app:"染料中间体（活性、酸性染料）"}},
{id:76,cas:"81-16-3",cat:"Dyes",en:{name:"Tobias acid",app:"Azo dye intermediates"},cn:{name:"托拜厄斯酸 (吐氏酸)",app:"偶氮染料中间体"}},
{id:78,cas:"135-19-3",cat:"Dyes",en:{name:"Beta naphthol",app:"Dyes, Pigments, Rubber antioxidants, Fragrances"},cn:{name:"β-萘酚",app:"染料、颜料、橡胶防老剂"}},
{id:79,cas:"121-57-3",cat:"Dyes",en:{name:"Sulphanilic acid",app:"Acid/Direct/Reactive dye intermediates"},cn:{name:"对氨基苯磺酸",app:"酸性/直接/活性染料中间体"}},
{id:80,cas:"482-89-3",cat:"Dyes",en:{name:"Indigo blue",app:"Textile dyeing (Denim)"},cn:{name:"靛蓝",app:"牛仔布染色"}},
{id:83,cas:"612-83-9",cat:"Dyes",en:{name:"DCB",app:"Organic pigments"},cn:{name:"3,3'-二氯联苯胺 (DCB)",app:"有机颜料"}},
{id:84,cas:"104-15-4",cat:"Additives",en:{name:"PTSA (p-Toluenesulfonic acid)",app:"Acid catalysts for Resins (Phenolic, Melamine)"},cn:{name:"对甲苯磺酸 (PTSA)",app:"树脂合成酸性催化剂"}},
{id:86,cas:"62-56-6",cat:"Pharma",en:{name:"Thiourea",app:"Pharma, Dyes, Electroplating"},cn:{name:"硫脲",app:"医药、染料、电镀"}},
{id:89,cas:"459-57-4",cat:"Pharma",en:{name:"4-Fluorobenzaldehyde",app:"Pharmaceuticals, Agrochemicals (Herbicides)"},cn:{name:"4-氟苯甲醛",app:"医药、农药（除草剂）"}},
{id:90,cas:"68-12-2",cat:"Solvents",en:{name:"N,N-Dimethylformamide (DMF)",app:"PU leather solvents, Fiber spinning, Petrochemicals"},cn:{name:"二甲基甲酰胺 (DMF)",app:"合成革浆料、纤维纺丝"}},
{id:91,cas:"616-38-6",cat:"Solvents",en:{name:"Dimethyl carbonate (DMC)",app:"Lithium battery electrolytes, Polycarbonate synthesis"},cn:{name:"碳酸二甲酯 (DMC)",app:"锂电池电解液、聚碳酸酯"}},
{id:92,cas:"105-58-8",cat:"Solvents",en:{name:"Diethyl carbonate (DEC)",app:"Lithium battery electrolytes, Organic synthesis"},cn:{name:"碳酸二乙酯 (DEC)",app:"锂电池电解液、有机合成"}},
{id:93,cas:"31570-04-4",cat:"Additives",en:{name:"Antioxidant 168",app:"PP/PE Polymer processing"},cn:{name:"抗氧剂 168",app:"PP/PE 聚合物加工"}},
{id:94,cas:"9084-06-4",cat:"Dyes",en:{name:"Dispersant MF",app:"Disperse dyes, Concrete admixtures"},cn:{name:"分散剂 MF",app:"分散染料、混凝土外加剂"}},
{id:95,cas:"36290-04-7",cat:"Dyes",en:{name:"Dispersant NNO",app:"Disperse dyes processing"},cn:{name:"分散剂 NNO",app:"分散染料加工"}},
{id:96,cas:"768-66-1",cat:"Additives",en:{name:"2,2,6,6-Tetramethylpiperidine (HTMP)",app:"HALS (Light Stabilizers) intermediates"},cn:{name:"2,2,6,6-四甲基哌啶",app:"光稳定剂 (HALS) 中间体"}},
{id:100,cas:"52829-07-9",cat:"Additives",en:{name:"HALS 770",app:"Light stabilizers for Plastics/Coatings"},cn:{name:"光稳定剂 770",app:"塑料、涂料光稳定剂"}},
{id:101,cas:"70198-29-7",cat:"Additives",en:{name:"UV-622 (Chimassorb 944)",app:"Light stabilizers for Polyolefins"},cn:{name:"光稳定剂 UV-622",app:"聚烯烃光稳定剂"}},
{id:103,cas:"/",cat:"Additives",en:{name:"Polyether polyol",app:"Polyurethane (PU) production"},cn:{name:"聚醚多元醇",app:"聚氨酯 (PU) 生产"}},
{id:104,cas:"9046-10-0",cat:"Additives",en:{name:"Polyetheramine (PEA)",app:"Wind power composites, Coatings, Adhesives"},cn:{name:"聚醚胺 (PEA)",app:"风电叶片、涂料、胶粘剂"}},
{id:105,cas:"85-44-9",cat:"Additives",en:{name:"Phthalic anhydride",app:"Plasticizers, UPR Resins, Dyes"},cn:{name:"苯酐",app:"增塑剂、不饱和树脂、染料"}},
{id:106,cas:"108-31-6",cat:"Additives",en:{name:"Maleic anhydride",app:"UPR Resins, Water reducers, Agrochemicals"},cn:{name:"马来酸酐 (顺酐)",app:"不饱和树脂、减水剂、农药"}},
{id:117,cas:"77-78-1",cat:"Pharma",en:{name:"Dimethyl sulfate (DMS)",app:"Methylation agents (Pharma/Agro/Dyes)"},cn:{name:"硫酸二甲酯 (DMS)",app:"甲基化剂（医药/农药/染料）"}},
{id:118,cas:"108-21-4",cat:"Solvents",en:{name:"Isopropyl Acetate",app:"Coatings, Inks, Pharma solvents"},cn:{name:"乙酸异丙酯",app:"涂料、油墨、医药溶剂"}},
{id:119,cas:"105-46-4",cat:"Solvents",en:{name:"Sec-Butyl acetate",app:"Coatings, Inks, Adhesives"},cn:{name:"乙酸仲丁酯",app:"涂料、油墨、胶粘剂"}},
{id:120,cas:"110-54-3",cat:"Solvents",en:{name:"N-Hexane",app:"Vegetable oil extraction, Solvents"},cn:{name:"正己烷",app:"植物油萃取、溶剂"}},
{id:121,cas:"142-82-5",cat:"Solvents",en:{name:"N-Heptane",app:"Standard reagents, Pharma solvents"},cn:{name:"正庚烷",app:"标准试剂、医药溶剂"}},
{id:122,cas:"68479-98-1",cat:"Additives",en:{name:"Diethyltoluenediamine (DETDA)",app:"PU Elastomers curing agents, Epoxy hardeners"},cn:{name:"二乙基甲苯二胺 (DETDA)",app:"聚氨酯扩链剂、环氧固化剂"}},
{id:123,cas:"7723-14-0",cat:"Additives",en:{name:"Red phosphorus",app:"Flame retardants, Organic synthesis"},cn:{name:"红磷",app:"阻燃剂、有机合成"}},
{id:124,cas:"128-37-0",cat:"Additives",en:{name:"Butylated hydroxytoluene (BHT)",app:"Antioxidants for Food/Plastics/Rubber"},cn:{name:"抗氧剂 BHT (264)",app:"食品/塑料/橡胶抗氧剂"}},
{id:125,cas:"35948-25-5",cat:"Additives",en:{name:"DOPO",app:"Flame retardant intermediates"},cn:{name:"DOPO",app:"阻燃剂中间体"}},
{id:126,cas:"80-05-7",cat:"Additives",en:{name:"Bisphenol-A",app:"Polycarbonate (PC), Epoxy resins"},cn:{name:"双酚A",app:"聚碳酸酯 (PC)、环氧树脂"}},
{id:130,cas:"121-44-8",cat:"Solvents",en:{name:"Triethylamine",app:"Catalysts, Solvents"},cn:{name:"三乙胺",app:"催化剂、溶剂"}},
{id:131,cas:"102-71-6",cat:"Additives",en:{name:"Triethanolamine",app:"Surfactants, Cement grinding aids"},cn:{name:"三乙醇胺",app:"表面活性剂、水泥助磨剂"}},
{id:134,cas:"108-30-5",cat:"Additives",en:{name:"Succinic anhydride",app:"Alkyd resins, Pharma/Agro intermediates"},cn:{name:"琥珀酸酐",app:"醇酸树脂、医药农药中间体"}},
{id:135,cas:"/",cat:"Additives",en:{name:"Epoxy resin",app:"Coatings, Composites, Adhesives, Flooring"},cn:{name:"环氧树脂",app:"涂料、复合材料、胶粘剂"}},
{id:139,cas:"67-63-0",cat:"Solvents",en:{name:"Isopropanol (IPA)",app:"Disinfectants, Solvents, Electronics cleaning"},cn:{name:"异丙醇 (IPA)",app:"消毒剂、溶剂、电子清洗"}},
{id:140,cas:"123-42-2",cat:"Solvents",en:{name:"Diacetone Alcohol",app:"Solvents for Coatings/Inks"},cn:{name:"双丙酮醇",app:"涂料油墨溶剂"}},
{id:141,cas:"107-21-1",cat:"Solvents",en:{name:"Ethylene glycol (MEG)",app:"Polyester fibers, Antifreeze"},cn:{name:"乙二醇 (MEG)",app:"聚酯纤维、防冻液"}},
{id:142,cas:"111-46-6",cat:"Solvents",en:{name:"Diethylene glycol (DEG)",app:"UPR resins, Plasticizers, Dehydration agents"},cn:{name:"二甘醇 (DEG)",app:"不饱和树脂、增塑剂、脱水剂"}},
{id:143,cas:"108-94-1",cat:"Solvents",en:{name:"Cyclohexanone",app:"Caprolactam/Adipic acid production, Solvents"},cn:{name:"环己酮",app:"己内酰胺/己二酸原料、溶剂"}},
{id:144,cas:"110-63-4",cat:"Solvents",en:{name:"1,4-butanediol (BDO)",app:"THF, PBT, GBL, PU production"},cn:{name:"1,4-丁二醇 (BDO)",app:"THF, PBT, GBL, PU 生产"}},
{id:145,cas:"25190-06-1",cat:"Additives",en:{name:"PTMEG",app:"Spandex fibers, PU Elastomers"},cn:{name:"聚四氢呋喃 (PTMEG)",app:"氨纶纤维、PU弹性体"}},
{id:148,cas:"110-05-4",cat:"Additives",en:{name:"Di-tert-butyl peroxide (DTBP)",app:"Crosslinking agents, Polymerization initiators"},cn:{name:"过氧化二叔丁酯 (DTBP)",app:"交联剂、聚合引发剂"}},
{id:149,cas:"27247-96-7",cat:"Additives",en:{name:"Isooctyl Nitrate",app:"Diesel Cetane improvers"},cn:{name:"硝酸异辛酯",app:"柴油十六烷值改进剂"}}
];